name: Pull Request Checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  prettier:
    runs-on: ubuntu-latest
    name: Check for Linting Errors
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM Install
        run: npm install --only-dev
        shell: bash

      - name: Check for Prettier Issues
        run: npm run prettier

  build:
    runs-on: ubuntu-latest
    name: Check Building
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM Install
        run: npm install
        shell: bash

      - name: Build
        run: npm run build
        shell: bash
